version: '3.5'
services:
  web-server:
    image: test-user1
    container_name: test-compose
    volumes:
      - '/usr/share/nginx/html:/usr/share/nginx/html'
    environment:
      - 'NGINX_HOST=sandbox.localhost'
      - 'NGINX_PORT=80'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
networks:
  default:
    driver: bridge
    name: webnet