version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app

  backend:
    build: /backend/
    volumes:
      - ./backend:/var/www/html/
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - '8000:80'
    restart: always
    depends_on:
      - mysql
    networks:
      - database
      - app

  mysql:
    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
#      - ./ProLearn.sql:/docker-entrypoint-initdb.d/prolearn.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '3306:80'
    environment:
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysql
    networks:
      - database

networks:
  database:
    name: database
  app:
    name: app
    driver: bridge