version: '3.7'
services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - '8000:8000'
    networks:
      - app-network
      - db

  apache:
    build: './apache2'
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www
    ports:
      - '9000:80'
      - '5000:5000'

  appdb:
    image: mariadb:10.8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./ProLearn.sql:/docker-entrypoint-prolearn.d
    ports:
      - '3306:3306'
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: appdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - appdb
    ports:
      - '8443:80'
    networks:
      - db

networks:
  app-network:
    driver: bridge
    
  db: